name: debian-base-loong64

on:
  push:
    paths:
      - 'images/build/debian-base/**'
      - '.github/workflows/debian-base-loong64.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: loongarch64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to Docker
        uses: docker/login-action@v4
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push debian-base image for loong64
        env:
          ARCH: loong64
          QEMUIMAGE: xfan1024/qemu-user-static
          QEMUVERSION: latest
          QEMUFLAGS:
          BASEIMAGE: ghcr.io/loong64/debian:trixie-slim
          REGISTRY: registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn
          IMAGE_VERSION: bookworm-v1.0.6
        run: |
          cd images/build/debian-base
          make push
